/*
 * EJBGeneratorGUIView.java
 */

package ejbgeneratorgui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */


public class EJBGeneratorGUIView extends FrameView {
    
    JFileChooser fc = new JFileChooser();

    public EJBGeneratorGUIView(SingleFrameApplication app) {
        super(app);

        getFrame().setResizable(false);
        //getFrame().pack();
                
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        jdkTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jdkButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        glassFishTextField = new javax.swing.JTextField();
        glassFishButton = new javax.swing.JButton();
        compileButton = new javax.swing.JButton();
        packButton = new javax.swing.JButton();
        deployButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        satusLabel = new javax.swing.JLabel();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ejbgeneratorgui.EJBGeneratorGUIApp.class).getContext().getResourceMap(EJBGeneratorGUIView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        inputTextField.setText(resourceMap.getString("inputTextField.text")); // NOI18N
        inputTextField.setName("inputTextField"); // NOI18N

        openButton.setText(resourceMap.getString("openButton.text")); // NOI18N
        openButton.setName("openButton"); // NOI18N
        openButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openButtonMouseClicked(evt);
            }
        });

        generateButton.setText(resourceMap.getString("generateButton.text")); // NOI18N
        generateButton.setName("generateButton"); // NOI18N
        generateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateButtonMouseClicked(evt);
            }
        });

        jdkTextField.setText(resourceMap.getString("jdkTextField.text")); // NOI18N
        jdkTextField.setName("jdkTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jdkButton.setText(resourceMap.getString("jdkButton.text")); // NOI18N
        jdkButton.setName("jdkButton"); // NOI18N
        jdkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdkButtonMouseClicked(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        glassFishTextField.setText(resourceMap.getString("glassFishTextField.text")); // NOI18N
        glassFishTextField.setName("glassFishTextField"); // NOI18N

        glassFishButton.setText(resourceMap.getString("glassFishButton.text")); // NOI18N
        glassFishButton.setName("glassFishButton"); // NOI18N
        glassFishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                glassFishButtonMouseClicked(evt);
            }
        });

        compileButton.setText(resourceMap.getString("compileButton.text")); // NOI18N
        compileButton.setName("compileButton"); // NOI18N
        compileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compileButtonMouseClicked(evt);
            }
        });

        packButton.setText(resourceMap.getString("packButton.text")); // NOI18N
        packButton.setName("packButton"); // NOI18N
        packButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packButtonMouseClicked(evt);
            }
        });

        deployButton.setText(resourceMap.getString("deployButton.text")); // NOI18N
        deployButton.setName("deployButton"); // NOI18N
        deployButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deployButtonMouseClicked(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        satusLabel.setText(resourceMap.getString("satusLabel.text")); // NOI18N
        satusLabel.setToolTipText(resourceMap.getString("satusLabel.toolTipText")); // NOI18N
        satusLabel.setName("satusLabel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(jdkTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(glassFishTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(packButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(deployButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(compileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                        .addGap(10, 10, 10)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jdkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(glassFishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satusLabel)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jdkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdkButton))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(glassFishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glassFishButton))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(satusLabel))
                .addGap(7, 7, 7)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton)
                    .addComponent(compileButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packButton)
                    .addComponent(deployButton))
                .addContainerGap())
        );

        openButton.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton1.AccessibleContext.accessibleName")); // NOI18N

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

private void openButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openButtonMouseClicked

    fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnVal = fc.showOpenDialog(null);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        inputTextField.setText(fc.getSelectedFile().getAbsolutePath());
        //This is where a real application would open the file.

    } else {
    }

    
}//GEN-LAST:event_openButtonMouseClicked

private void generateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateButtonMouseClicked
        try {
            ProcessBuilder builder = new ProcessBuilder(
                    "cmd.exe", "/c", "ruby EJBGenerator.rb generate \"" + inputTextField.getText() + "\"");
                builder.redirectErrorStream(true);
                Process p = builder.start();
                BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line;
                while (true) {
                    line = r.readLine();
                    if (line == null) { break; }
                    System.out.println(line);
                }
        } catch (IOException ex) {
            Logger.getLogger(EJBGeneratorGUIView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_generateButtonMouseClicked

private void compileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compileButtonMouseClicked

    try {
            ProcessBuilder builder = new ProcessBuilder(
                    "cmd.exe", "/c", "ruby EJBGenerator.rb compile \"" + jdkTextField.getText() + "\" \"" + glassFishTextField.getText() + "\" \"" + inputTextField.getText() + "\"");
                builder.redirectErrorStream(true);
                Process p = builder.start();
                BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line;
                while (true) {
                    line = r.readLine();
                    if (line == null) { break; }
                    System.out.println(line);
                }
        } catch (IOException ex) {
            Logger.getLogger(EJBGeneratorGUIView.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_compileButtonMouseClicked

private void packButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packButtonMouseClicked

    try {
            ProcessBuilder builder = new ProcessBuilder(
                    "cmd.exe", "/c", "ruby EJBGenerator.rb pack \"" + jdkTextField.getText() + "\" \"" + inputTextField.getText() + "\"");
                builder.redirectErrorStream(true);
                Process p = builder.start();
                BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line;
                while (true) {
                    line = r.readLine();
                    if (line == null) { break; }
                    System.out.println(line);
                }
        } catch (IOException ex) {
            Logger.getLogger(EJBGeneratorGUIView.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_packButtonMouseClicked

private void deployButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deployButtonMouseClicked

  try {
            ProcessBuilder builder = new ProcessBuilder(
                    "cmd.exe", "/c", "ruby EJBGenerator.rb deploy \"" + glassFishTextField.getText() + "\" \"" + inputTextField.getText() + "\"");
                builder.redirectErrorStream(true);
                Process p = builder.start();
                BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line;
                while (true) {
                    line = r.readLine();
                    if (line == null) { break; }
                    System.out.println(line);
                }
        } catch (IOException ex) {
            Logger.getLogger(EJBGeneratorGUIView.class.getName()).log(Level.SEVERE, null, ex);
        }

    
}//GEN-LAST:event_deployButtonMouseClicked

private void jdkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdkButtonMouseClicked

    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = fc.showOpenDialog(null);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        jdkTextField.setText(fc.getSelectedFile().getAbsolutePath());
        //This is where a real application would open the file.

    } else {
    }
    
}//GEN-LAST:event_jdkButtonMouseClicked

private void glassFishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glassFishButtonMouseClicked

    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = fc.showOpenDialog(null);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        glassFishTextField.setText(fc.getSelectedFile().getAbsolutePath());
        //This is where a real application would open the file.

    } else {
    }
    
}//GEN-LAST:event_glassFishButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compileButton;
    private javax.swing.JButton deployButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton glassFishButton;
    private javax.swing.JTextField glassFishTextField;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jdkButton;
    private javax.swing.JTextField jdkTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JButton packButton;
    private javax.swing.JLabel satusLabel;
    // End of variables declaration//GEN-END:variables

}
